/* Autogenerated by png2wx.pl on Sat Feb 11 00:12:56 2023 */
#ifndef NETWORK_PI_ICONS_H
#define NETWORK_PI_ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_network_colour;

#endif /* NETWORK_PI_ICONS_H */
