#define PLUGIN_VERSION_MAJOR 1
#define PLUGIN_VERSION_MINOR 0
#define PLUGIN_VERSION_PATCH 0
#define NAME_SUFFIX "ov5.0"
#define PLUGIN_VERSION_DATE "31/01/2023"
#define PLUGIN_PACKAGE_NAME "network_pi"
